version: 2.0
jobs:
    build:
      docker:
            - image: circleci/ruby:2.4.2-jessie-node
      parallelism: 16
      auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
      steps:
        - run: lscpu